/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PosTrackerRouteImport } from './routes/pos.tracker'
import { Route as PosTablesRouteImport } from './routes/pos.tables'
import { Route as PosSettingsRouteImport } from './routes/pos.settings'
import { Route as PosMenuAdminRouteImport } from './routes/pos.menu-admin'
import { Route as PosMenuRouteImport } from './routes/pos.menu'
import { Route as PosDisplayRouteImport } from './routes/pos.display'
import { Route as AdminSelfOrderingRouteImport } from './routes/admin.self-ordering'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminKdsRouteImport } from './routes/admin.kds'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminSTokenRouteImport } from './routes/admin.s.$token'

const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PosTrackerRoute = PosTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => PosRoute,
} as any)
const PosTablesRoute = PosTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => PosRoute,
} as any)
const PosSettingsRoute = PosSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PosRoute,
} as any)
const PosMenuAdminRoute = PosMenuAdminRouteImport.update({
  id: '/menu-admin',
  path: '/menu-admin',
  getParentRoute: () => PosRoute,
} as any)
const PosMenuRoute = PosMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PosRoute,
} as any)
const PosDisplayRoute = PosDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => PosRoute,
} as any)
const AdminSelfOrderingRoute = AdminSelfOrderingRouteImport.update({
  id: '/self-ordering',
  path: '/self-ordering',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKdsRoute = AdminKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSTokenRoute = AdminSTokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/kds': typeof AdminKdsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/self-ordering': typeof AdminSelfOrderingRoute
  '/pos/display': typeof PosDisplayRoute
  '/pos/menu': typeof PosMenuRoute
  '/pos/menu-admin': typeof PosMenuAdminRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/tables': typeof PosTablesRoute
  '/pos/tracker': typeof PosTrackerRoute
  '/admin/': typeof AdminIndexRoute
  '/pos/': typeof PosIndexRoute
  '/admin/s/$token': typeof AdminSTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/kds': typeof AdminKdsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/self-ordering': typeof AdminSelfOrderingRoute
  '/pos/display': typeof PosDisplayRoute
  '/pos/menu': typeof PosMenuRoute
  '/pos/menu-admin': typeof PosMenuAdminRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/tables': typeof PosTablesRoute
  '/pos/tracker': typeof PosTrackerRoute
  '/admin': typeof AdminIndexRoute
  '/pos': typeof PosIndexRoute
  '/admin/s/$token': typeof AdminSTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/kds': typeof AdminKdsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/self-ordering': typeof AdminSelfOrderingRoute
  '/pos/display': typeof PosDisplayRoute
  '/pos/menu': typeof PosMenuRoute
  '/pos/menu-admin': typeof PosMenuAdminRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/tables': typeof PosTablesRoute
  '/pos/tracker': typeof PosTrackerRoute
  '/admin/': typeof AdminIndexRoute
  '/pos/': typeof PosIndexRoute
  '/admin/s/$token': typeof AdminSTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/pos'
    | '/admin/coupons'
    | '/admin/kds'
    | '/admin/promotions'
    | '/admin/self-ordering'
    | '/pos/display'
    | '/pos/menu'
    | '/pos/menu-admin'
    | '/pos/settings'
    | '/pos/tables'
    | '/pos/tracker'
    | '/admin/'
    | '/pos/'
    | '/admin/s/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/coupons'
    | '/admin/kds'
    | '/admin/promotions'
    | '/admin/self-ordering'
    | '/pos/display'
    | '/pos/menu'
    | '/pos/menu-admin'
    | '/pos/settings'
    | '/pos/tables'
    | '/pos/tracker'
    | '/admin'
    | '/pos'
    | '/admin/s/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/pos'
    | '/admin/coupons'
    | '/admin/kds'
    | '/admin/promotions'
    | '/admin/self-ordering'
    | '/pos/display'
    | '/pos/menu'
    | '/pos/menu-admin'
    | '/pos/settings'
    | '/pos/tables'
    | '/pos/tracker'
    | '/admin/'
    | '/pos/'
    | '/admin/s/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pos/tracker': {
      id: '/pos/tracker'
      path: '/tracker'
      fullPath: '/pos/tracker'
      preLoaderRoute: typeof PosTrackerRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/tables': {
      id: '/pos/tables'
      path: '/tables'
      fullPath: '/pos/tables'
      preLoaderRoute: typeof PosTablesRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/settings': {
      id: '/pos/settings'
      path: '/settings'
      fullPath: '/pos/settings'
      preLoaderRoute: typeof PosSettingsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/menu-admin': {
      id: '/pos/menu-admin'
      path: '/menu-admin'
      fullPath: '/pos/menu-admin'
      preLoaderRoute: typeof PosMenuAdminRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/menu': {
      id: '/pos/menu'
      path: '/menu'
      fullPath: '/pos/menu'
      preLoaderRoute: typeof PosMenuRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/display': {
      id: '/pos/display'
      path: '/display'
      fullPath: '/pos/display'
      preLoaderRoute: typeof PosDisplayRouteImport
      parentRoute: typeof PosRoute
    }
    '/admin/self-ordering': {
      id: '/admin/self-ordering'
      path: '/self-ordering'
      fullPath: '/admin/self-ordering'
      preLoaderRoute: typeof AdminSelfOrderingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kds': {
      id: '/admin/kds'
      path: '/kds'
      fullPath: '/admin/kds'
      preLoaderRoute: typeof AdminKdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/s/$token': {
      id: '/admin/s/$token'
      path: '/s/$token'
      fullPath: '/admin/s/$token'
      preLoaderRoute: typeof AdminSTokenRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminKdsRoute: typeof AdminKdsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminSelfOrderingRoute: typeof AdminSelfOrderingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSTokenRoute: typeof AdminSTokenRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouponsRoute: AdminCouponsRoute,
  AdminKdsRoute: AdminKdsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminSelfOrderingRoute: AdminSelfOrderingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSTokenRoute: AdminSTokenRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PosRouteChildren {
  PosDisplayRoute: typeof PosDisplayRoute
  PosMenuRoute: typeof PosMenuRoute
  PosMenuAdminRoute: typeof PosMenuAdminRoute
  PosSettingsRoute: typeof PosSettingsRoute
  PosTablesRoute: typeof PosTablesRoute
  PosTrackerRoute: typeof PosTrackerRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosDisplayRoute: PosDisplayRoute,
  PosMenuRoute: PosMenuRoute,
  PosMenuAdminRoute: PosMenuAdminRoute,
  PosSettingsRoute: PosSettingsRoute,
  PosTablesRoute: PosTablesRoute,
  PosTrackerRoute: PosTrackerRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PosRoute: PosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
