import type { MenuItem, Table, InventoryItem, User } from "./types";

export const seedUsers: User[] = [
  {
    id: "u1",
    name: "Alex Admin",
    email: "admin@OdooCafé.test",
    role: "admin",
    pin: "1111",
    twoFactorEnabled: false,
    username: "Admin",
    password: "Admin@123",
  },
  {
    id: "u2",
    name: "Maria Manager",
    email: "manager@OdooCafé.test",
    role: "manager",
    pin: "2222",
    username: "manager",
    password: "password123",
  },
  {
    id: "u3",
    name: "Sam Server",
    email: "server@OdooCafé.test",
    role: "server",
    pin: "3333",
    username: "server",
    password: "password123",
  },
  {
    id: "u4",
    name: "Casey Cashier",
    email: "cashier@OdooCafé.test",
    role: "cashier",
    pin: "4444",
    username: "cashier",
    password: "password123",
  },
  {
    id: "u5",
    name: "Surya Prakash",
    email: "suryaprakashd22007@gmail.com",
    role: "customer",
    pin: "5555",
    username: "suryaprakash",
    password: "password123",
  },
  {
    id: "u6",
    name: "Caleb",
    email: "caleb@odoocafe.local",
    role: "server",
    pin: "6666",
    username: "Caleb",
    password: "student@123",
  },
  {
    id: "u7",
    name: "dummy",
    email: "dummy@odoocafe.local",
    role: "customer",
    pin: "7777",
    username: "dummy",
    password: "password12345678",
  },
];

export const seedInventory: InventoryItem[] = [
  { id: "inv-bun", name: "Brioche bun", unit: "ea", qty: 80, parLevel: 40 },
  { id: "inv-patty", name: "Beef patty", unit: "ea", qty: 60, parLevel: 30 },
  { id: "inv-cheese", name: "Cheddar slice", unit: "ea", qty: 100, parLevel: 50 },
  { id: "inv-fries", name: "Fries portion", unit: "ea", qty: 120, parLevel: 60 },
  { id: "inv-dough", name: "Pizza dough", unit: "ea", qty: 40, parLevel: 20 },
  { id: "inv-mozz", name: "Mozzarella (g)", unit: "g", qty: 5000, parLevel: 2000 },
  { id: "inv-pasta", name: "Pasta (g)", unit: "g", qty: 8000, parLevel: 3000 },
  { id: "inv-espresso", name: "Espresso shot", unit: "ea", qty: 200, parLevel: 80 },
  { id: "inv-wine", name: "Wine bottle", unit: "ea", qty: 24, parLevel: 12 },
];

export const seedMenu: MenuItem[] = [
  {
    id: "m1",
    name: "Masala Tea",
    description: "Spiced Indian chai brewed with ginger, cardamom & milk",
    price: 99,
    category: "Drinks",
    available: true,
    image: "/masala tea.jpeg",
  },
  {
    id: "m2",
    name: "Coffee",
    description: "Rich, freshly brewed coffee served hot or cold",
    price: 149,
    category: "Drinks",
    available: true,
    image: "/Coffee.jpeg",
  },
  {
    id: "m3",
    name: "Mango Lassi",
    description: "Creamy yoghurt blended with ripe Alphonso mangoes",
    price: 199,
    category: "Drinks",
    available: true,
    image: "/mango lassi.jpeg",
  },
  {
    id: "m4",
    name: "Blueberry Milkshake",
    description: "Thick, chilled milkshake bursting with fresh blueberries",
    price: 249,
    category: "Drinks",
    available: true,
    image: "/blue milkshake.jpeg",
  },
  {
    id: "m5",
    name: "Kunafa",
    description: "Crispy shredded pastry soaked in rose syrup with cheese",
    price: 349,
    category: "Desserts",
    available: true,
    image: "/Kunfa.jpeg",
  },
  {
    id: "m6",
    name: "Cheese Burger",
    description: "Juicy patty stacked with melted cheese, lettuce & sauce",
    price: 299,
    category: "Mains",
    available: true,
    image: "/cheese burger.jpeg",
  },
  {
    id: "m7",
    name: "Pizza",
    description: "Stone-baked pizza with fresh toppings and mozzarella",
    price: 499,
    category: "Mains",
    available: true,
    image: "/Pizza.jpeg",
  },
  {
    id: "m8",
    name: "Maggie",
    description: "Classic instant noodles tossed with veggies & masala",
    price: 129,
    category: "Mains",
    available: true,
    image: "/Maggie.jpeg",
  },
  {
    id: "m9",
    name: "Pani Puri",
    description: "Crispy puris filled with tangy tamarind and spiced water",
    price: 99,
    category: "Snacks",
    available: true,
    image: "/Pani Puri.jpeg",
  },
  {
    id: "m10",
    name: "Pav Bhaji",
    description: "Spiced vegetable mash served with buttery toasted buns",
    price: 199,
    category: "Mains",
    available: true,
    image: "/pav bhaji.jpeg",
  },
  {
    id: "m11",
    name: "Mojito",
    description: "Refreshing mint & lime cooler, virgin or classic",
    price: 179,
    category: "Drinks",
    available: true,
    image: "/mojito.jpeg",
  },
  {
    id: "m12",
    name: "Puff",
    description: "Flaky pastry puff filled with spiced potato or veg",
    price: 49,
    category: "Snacks",
    available: true,
    image: "/Puff.jpeg",
  },
  {
    id: "m13",
    name: "Cake",
    description: "Moist, freshly baked slices in seasonal flavours",
    price: 249,
    category: "Desserts",
    available: true,
    image: "/Cake.jpeg",
  },
  {
    id: "m14",
    name: "Ice Water",
    description: "Chilled mineral water served with a squeeze of lemon",
    price: 29,
    category: "Drinks",
    available: true,
    image: "/Ice water.jpeg",
  },
  {
    id: "m15",
    name: "Special Biryani",
    description: "Aromatic basmati rice cooked with secret spices",
    price: 399,
    category: "Mains",
    available: true,
    image: "/masala tea.jpeg",
  },
];

export const seedTables: Table[] = [
  { id: "t1", label: "1", seats: 2, x: 1, y: 1, token: "table-1", status: "free" },
  { id: "t2", label: "2", seats: 2, x: 2, y: 1, token: "table-2", status: "free" },
  { id: "t3", label: "3", seats: 4, x: 3, y: 1, token: "table-3", status: "free" },
  { id: "t4", label: "4", seats: 4, x: 4, y: 1, token: "table-4", status: "free" },
  { id: "t5", label: "5", seats: 6, x: 1, y: 2, token: "table-5", status: "free" },
  { id: "t6", label: "6", seats: 4, x: 2, y: 2, token: "table-6", status: "free" },
  { id: "t7", label: "7", seats: 2, x: 3, y: 2, token: "table-7", status: "free" },
  { id: "t8", label: "8", seats: 8, x: 4, y: 2, token: "table-8", status: "free" },
  { id: "t9", label: "Bar 1", seats: 1, x: 1, y: 3, token: "table-bar-1", status: "free" },
  { id: "t10", label: "Bar 2", seats: 1, x: 2, y: 3, token: "table-bar-2", status: "free" },
  { id: "t11", label: "Patio 1", seats: 4, x: 3, y: 3, token: "table-patio-1", status: "free" },
  { id: "t12", label: "Patio 2", seats: 4, x: 4, y: 3, token: "table-patio-2", status: "free" },
];

export const slideshowImages = [
  "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1600&q=80",
  "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1600&q=80",
  "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=1600&q=80",
  "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=1600&q=80",
  "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1600&q=80",
];
